name       : watchman
version    : 4.9.0
release    : 5
source     :
    - https://github.com/facebook/watchman/archive/v4.9.0.tar.gz : 1f6402dc70b1d056fffc3748f2fdcecff730d8843bb6936de395b3443ce05322
license    : Apache-2.0
component  : system.utils
homepage   : https://facebook.github.io/watchman
summary    : Watches files and records, or triggers actions, when they change
description: |
    Watchman exists to watch files and record when they actually change. It can also trigger actions (such as rebuilding assets) when matching file changes.
builddeps  :
    - pkgconfig(python3)
setup      : |
    %autogen --with-python=/usr/bin/python3 \
             --enable-statedir=/run/watchman
build      : |
    %make
install    : |
    %make_install
    rm -rfv $installdir/run
    install -Dm 644 $pkgfiles/watchman.tmpfiles $installdir%libdir%/tmpfiles.d/watchman.conf
